title: zhny's blog - zhny的博客
name: zhny's blog
email: zhangzhny1@gmail.com
description: 网名zhny，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/internetyi
keywords: Laravel,Laravel教程,Laravel安装,Laravel视频,Pinyin,汉字转拼音
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, RESTful, Stackoverflow, Sublime Text, OmniGaffale, OminiPlan]

timezone:    PRC
encoding: "utf-8"

url: http://blog.zhnytech.com
baseurl:  "/"
domain:    blog.zhnytech.com
permalink:     /articles/:year/:month/:day/:title.html
paginate_path: 'page/:num'
paginate:   10
source_code: https://github.com/internetyi/internetyi.github.io
static: http://static.zhnytech.com/blog

# Build settings
#markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-html-pipeline
  

disqus:
  id: zhny

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source.html
    label: Open-Source

  -
    href: https://github.com/internetyi
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/internetyi
    label: Weibo
    target: _blank

  -
    href: /bookmark.html
    label: Bookmark

  -
    href: /about.html
    label: About

popular_repos: ['pinyin', 'wechat', 'writor', 'laravel-wechat', 'laravel-lang', 'laravel-pinyin', 'latest-laravel', 'latest-lumen']
contribute_repos: ['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']