title: zhny's Blog - 关注网站开发的个人技术博客
name: zhny's Blog
email: zhangzhny1@gmail.com
description: 网名zhny，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/internetyi
keywords: Laravel,技术博客,PHP笔记,web 开发笔记,技术分享,zhny,zhny‘s Blog
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, RESTful, Stackoverflow, Sublime Text, OmniGaffale, OminiPlan]

timezone: PRC
encoding: "utf-8"

url: https://blog.zhnytech.com
baseurl: "/"
domain: blog.zhnytech.com
permalink: /articles/:year/:month/:day/:title.html
paginate_path: 'page/:num'
paginate: 10
source_code: https://github.com/internetyi/internetyi.github.io
static: https://static.zhnytech.com/blog

# Build settings
markdown: kramdown
highlighter: true
#lsi: true
excerpt_separator: "\n\n"

source: .
destination: ./_site

quiet: true
defaults: []

redcarpet:
  extensions:
    - tables
    - autolink
    - fenced_code_blocks
    - no_intra_emphasis
    - smart
  with_toc_data: true

kramdown:
  input: GFM
  extensions:
    - tables
    - autolink
    - footnotes
    - smart
  autolink : true
  enable_coderay: true
  toc_levels: "1,2,3,4,5,6" 
  enable_coderay: true
  auto_ids: true
  footnote_nr: 1
  syntax_highlighter: rouge
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  coderay:
    # coderay_line_numbers:  nil
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style


gems:
  - jemoji
  - rouge
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  #- jekyll-html-pipeline


disqus:
  id: zhny

google:
    analytics_id: UA-55452630-1

# navigations
navs:
  -
    href: /
    label: Home

  -
    href: /open-source.html
    label: Open-Source

  -
    href: https://github.com/internetyi
    label: GitHub
    target: _blank
    outlink: true

  -
    href: http://weibo.com/internetyi
    label: Weibo
    target: _blank
    outlink: true

  -
    href: /bookmark.html
    label: Bookmark

  -
    href: /about.html
    label: About

popular_repos: ['pinyin', 'wechat', 'writor', 'laravel-wechat', 'laravel-lang', 'laravel-pinyin', 'latest-laravel', 'latest-lumen']
contribute_repos: ['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']